import { MigrationInterface, QueryRunner } from "typeorm";

export class TableName1764248467474 implements MigrationInterface {
    name = 'TableName1764248467474'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "follows" ("follow_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "followerId" uuid, "followingId" uuid, CONSTRAINT "UQ_105079775692df1f8799ed0fac8" UNIQUE ("followerId", "followingId"), CONSTRAINT "PK_216b46abae15bf5368d90a1116a" PRIMARY KEY ("follow_id"))`);
        await queryRunner.query(`CREATE TABLE "audio" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "category" character varying NOT NULL, "author" character varying NOT NULL, CONSTRAINT "PK_dbb3222220cebc1deb5a2988062" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "hashtag" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tag" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d08e011257d7cba6df34c553133" UNIQUE ("tag"), CONSTRAINT "PK_cb36eb8af8412bfa978f1165d78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bookmarks" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "userId" uuid, CONSTRAINT "UQ_1b54edf804b807e71c195f20c28" UNIQUE ("userId", "name"), CONSTRAINT "PK_7f976ef6cecd37a53bd11685f32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "reelUuid" uuid, "authorId" uuid, "parentId" uuid, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."video_type_enum" AS ENUM('news', 'story', 'reels')`);
        await queryRunner.query(`CREATE TABLE "video" ("uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "caption" character varying, "videoUrl" character varying NOT NULL, "thumbnailUrl" text, "externalAudioSrc" character varying, "type" "public"."video_type_enum" NOT NULL, "audio_trim_from" character varying, "audio_trim_to" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "archived" boolean NOT NULL DEFAULT false, "userIdId" uuid, "audioUuid" uuid, CONSTRAINT "PK_d80bea611910b0495fa043fe64c" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "likes" ("like_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "reelUuid" uuid, "userId" uuid, CONSTRAINT "UQ_436f59d019b1b45f2f35794ce76" UNIQUE ("userId", "reelUuid"), CONSTRAINT "PK_4b698ab917e6a07411bb250e597" PRIMARY KEY ("like_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notification_type_enum" AS ENUM('LIKE', 'COMMENT', 'FOLLOW', 'MENTION', 'MESSAGE')`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."notification_type_enum" NOT NULL, "message" text, "referenceId" uuid, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "recipientId" uuid, "senderId" uuid, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_star_enum" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`CREATE TABLE "user_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "ProfilePicture" character varying DEFAULT '', "bio" character varying DEFAULT '', "name" character varying DEFAULT '', "url" character varying DEFAULT '', "paid" boolean NOT NULL DEFAULT false, "role" character varying NOT NULL DEFAULT 'user', "star" "public"."user_profile_star_enum" NOT NULL DEFAULT '0', CONSTRAINT "UQ_eee360f3bff24af1b6890765201" UNIQUE ("user_id"), CONSTRAINT "REL_eee360f3bff24af1b689076520" UNIQUE ("user_id"), CONSTRAINT "PK_f44d0cd18cfd80b0fed7806c3b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "UQ_6a8ca5961656d13c16c04079dd3" UNIQUE ("token"), CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chats" ("chat_id" SERIAL NOT NULL, "message_text" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_for" json, "sessionSessionId" integer, "senderId" uuid, CONSTRAINT "PK_cb573d310bde330521e7715db2a" PRIMARY KEY ("chat_id"))`);
        await queryRunner.query(`CREATE TABLE "chat_sessions" ("session_id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user1Id" uuid, "user2Id" uuid, CONSTRAINT "PK_6ccb7b732f5af0bde672165cadf" PRIMARY KEY ("session_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying, "phone_no" character varying, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "refreshToken" text, "resetToken" text, "resetTokenExpiry" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_e84ed8eafd2812aaf53a33064d2" UNIQUE ("phone_no"), CONSTRAINT "CHK_41d91c86726166da8af76b75b7" CHECK ("email" IS NOT NULL OR "phone_no" IS NOT NULL), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "views" ("view_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "reelUuid" uuid, CONSTRAINT "UQ_3f55d3b02734107e13db5ea22ee" UNIQUE ("userId", "reelUuid"), CONSTRAINT "PK_fcc7ae614addd3b3fc03dd22d21" PRIMARY KEY ("view_id"))`);
        await queryRunner.query(`CREATE TABLE "block" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "blockedById" uuid, "blockedUserId" uuid, CONSTRAINT "UQ_4e7a9007a6f481f257d2a55e361" UNIQUE ("blockedById", "blockedUserId"), CONSTRAINT "PK_d0925763efb591c2e2ffb267572" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shares" ("share_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reel_id" uuid NOT NULL, "user_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_561becd0e5f2403c623466c7ae6" UNIQUE ("user_id", "reel_id"), CONSTRAINT "PK_331c68d8b4c85f04c290633f576" PRIMARY KEY ("share_id"))`);
        await queryRunner.query(`CREATE TABLE "otp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying, "email" character varying, "phone_no" character varying, "code" character varying(6) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_32556d9d7b22031d7d0e1fd6723" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bookmark_reels" ("bookmark_id" integer NOT NULL, "reel_id" uuid NOT NULL, CONSTRAINT "PK_bc720a170bfc97ccab738aaf04d" PRIMARY KEY ("bookmark_id", "reel_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bf5b05a1450ae8049082928f85" ON "bookmark_reels" ("bookmark_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9512bb3043bc3aa26944df0f17" ON "bookmark_reels" ("reel_id") `);
        await queryRunner.query(`CREATE TABLE "comment_mentions" ("commentId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_11054ceba1bed401adbb83b8fbb" PRIMARY KEY ("commentId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dc73b25397fe92549b4c41dfe5" ON "comment_mentions" ("commentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0294c9da809e60b4f2472d4c83" ON "comment_mentions" ("userId") `);
        await queryRunner.query(`CREATE TABLE "comment_likes" ("commentId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_ec6698ead14ad945033ebb2f1b9" PRIMARY KEY ("commentId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_abbd506a94a424dd6a3a68d26f" ON "comment_likes" ("commentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_34d1f902a8a527dbc2502f87c8" ON "comment_likes" ("userId") `);
        await queryRunner.query(`CREATE TABLE "video_mentions_users" ("videoUuid" uuid NOT NULL, "usersId" uuid NOT NULL, CONSTRAINT "PK_5e4ba84731a1f68dd8a90e402a9" PRIMARY KEY ("videoUuid", "usersId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91df686c1a7cf8e715dfbf1e27" ON "video_mentions_users" ("videoUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_c4000d356708cf16c3637ff160" ON "video_mentions_users" ("usersId") `);
        await queryRunner.query(`CREATE TABLE "video_hashtags_hashtag" ("videoUuid" uuid NOT NULL, "hashtagId" uuid NOT NULL, CONSTRAINT "PK_8ce68672a48cafd45608c6a02af" PRIMARY KEY ("videoUuid", "hashtagId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c63a58631cc618498c506732d" ON "video_hashtags_hashtag" ("videoUuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_c19d0490a6b115b54d749da44e" ON "video_hashtags_hashtag" ("hashtagId") `);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb" FOREIGN KEY ("followingId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmarks" ADD CONSTRAINT "FK_c6065536f2f6de3a0163e19a584" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_459dcb86c41a845ece74a282086" FOREIGN KEY ("reelUuid") REFERENCES "video"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_276779da446413a0d79598d4fbd" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_e3aebe2bd1c53467a07109be596" FOREIGN KEY ("parentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_550d619ef9610080a3f9e175edf" FOREIGN KEY ("userIdId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "video" ADD CONSTRAINT "FK_479578acd284d68c48b609768b8" FOREIGN KEY ("audioUuid") REFERENCES "audio"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_d2936a168263a7fd6be1b6d3d45" FOREIGN KEY ("reelUuid") REFERENCES "video"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "likes" ADD CONSTRAINT "FK_cfd8e81fac09d7339a32e57d904" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_ab7cbe7a013ecac5da0a8f88884" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_c0af34102c13c654955a0c5078b" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_profile" ADD CONSTRAINT "FK_eee360f3bff24af1b6890765201" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_2d1c19d121d008d08d8a3bcf221" FOREIGN KEY ("sessionSessionId") REFERENCES "chat_sessions"("session_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chats" ADD CONSTRAINT "FK_d697f19c9c7778ed773b449ce70" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_25a3d1f613a878ada3e2383fcc8" FOREIGN KEY ("user1Id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" ADD CONSTRAINT "FK_44d3b8a849cb98234fe33582e61" FOREIGN KEY ("user2Id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "views" ADD CONSTRAINT "FK_1a136367d53567a43ba7aae5a7b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "views" ADD CONSTRAINT "FK_ca481eee1cdb2daeb68d5faf532" FOREIGN KEY ("reelUuid") REFERENCES "video"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "block" ADD CONSTRAINT "FK_ce5e8e4e78c2457ad70de349e40" FOREIGN KEY ("blockedById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "block" ADD CONSTRAINT "FK_c9a8df2f7cbbae1cda940694409" FOREIGN KEY ("blockedUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookmark_reels" ADD CONSTRAINT "FK_bf5b05a1450ae8049082928f857" FOREIGN KEY ("bookmark_id") REFERENCES "bookmarks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bookmark_reels" ADD CONSTRAINT "FK_9512bb3043bc3aa26944df0f17c" FOREIGN KEY ("reel_id") REFERENCES "video"("uuid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" ADD CONSTRAINT "FK_dc73b25397fe92549b4c41dfe56" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" ADD CONSTRAINT "FK_0294c9da809e60b4f2472d4c835" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_likes" ADD CONSTRAINT "FK_abbd506a94a424dd6a3a68d26f4" FOREIGN KEY ("commentId") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comment_likes" ADD CONSTRAINT "FK_34d1f902a8a527dbc2502f87c88" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "video_mentions_users" ADD CONSTRAINT "FK_91df686c1a7cf8e715dfbf1e27b" FOREIGN KEY ("videoUuid") REFERENCES "video"("uuid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "video_mentions_users" ADD CONSTRAINT "FK_c4000d356708cf16c3637ff160e" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "video_hashtags_hashtag" ADD CONSTRAINT "FK_8c63a58631cc618498c506732d4" FOREIGN KEY ("videoUuid") REFERENCES "video"("uuid") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "video_hashtags_hashtag" ADD CONSTRAINT "FK_c19d0490a6b115b54d749da44ec" FOREIGN KEY ("hashtagId") REFERENCES "hashtag"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "video_hashtags_hashtag" DROP CONSTRAINT "FK_c19d0490a6b115b54d749da44ec"`);
        await queryRunner.query(`ALTER TABLE "video_hashtags_hashtag" DROP CONSTRAINT "FK_8c63a58631cc618498c506732d4"`);
        await queryRunner.query(`ALTER TABLE "video_mentions_users" DROP CONSTRAINT "FK_c4000d356708cf16c3637ff160e"`);
        await queryRunner.query(`ALTER TABLE "video_mentions_users" DROP CONSTRAINT "FK_91df686c1a7cf8e715dfbf1e27b"`);
        await queryRunner.query(`ALTER TABLE "comment_likes" DROP CONSTRAINT "FK_34d1f902a8a527dbc2502f87c88"`);
        await queryRunner.query(`ALTER TABLE "comment_likes" DROP CONSTRAINT "FK_abbd506a94a424dd6a3a68d26f4"`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" DROP CONSTRAINT "FK_0294c9da809e60b4f2472d4c835"`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" DROP CONSTRAINT "FK_dc73b25397fe92549b4c41dfe56"`);
        await queryRunner.query(`ALTER TABLE "bookmark_reels" DROP CONSTRAINT "FK_9512bb3043bc3aa26944df0f17c"`);
        await queryRunner.query(`ALTER TABLE "bookmark_reels" DROP CONSTRAINT "FK_bf5b05a1450ae8049082928f857"`);
        await queryRunner.query(`ALTER TABLE "block" DROP CONSTRAINT "FK_c9a8df2f7cbbae1cda940694409"`);
        await queryRunner.query(`ALTER TABLE "block" DROP CONSTRAINT "FK_ce5e8e4e78c2457ad70de349e40"`);
        await queryRunner.query(`ALTER TABLE "views" DROP CONSTRAINT "FK_ca481eee1cdb2daeb68d5faf532"`);
        await queryRunner.query(`ALTER TABLE "views" DROP CONSTRAINT "FK_1a136367d53567a43ba7aae5a7b"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_44d3b8a849cb98234fe33582e61"`);
        await queryRunner.query(`ALTER TABLE "chat_sessions" DROP CONSTRAINT "FK_25a3d1f613a878ada3e2383fcc8"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_d697f19c9c7778ed773b449ce70"`);
        await queryRunner.query(`ALTER TABLE "chats" DROP CONSTRAINT "FK_2d1c19d121d008d08d8a3bcf221"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2"`);
        await queryRunner.query(`ALTER TABLE "user_profile" DROP CONSTRAINT "FK_eee360f3bff24af1b6890765201"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_c0af34102c13c654955a0c5078b"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_ab7cbe7a013ecac5da0a8f88884"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_cfd8e81fac09d7339a32e57d904"`);
        await queryRunner.query(`ALTER TABLE "likes" DROP CONSTRAINT "FK_d2936a168263a7fd6be1b6d3d45"`);
        await queryRunner.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_479578acd284d68c48b609768b8"`);
        await queryRunner.query(`ALTER TABLE "video" DROP CONSTRAINT "FK_550d619ef9610080a3f9e175edf"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_e3aebe2bd1c53467a07109be596"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_276779da446413a0d79598d4fbd"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_459dcb86c41a845ece74a282086"`);
        await queryRunner.query(`ALTER TABLE "bookmarks" DROP CONSTRAINT "FK_c6065536f2f6de3a0163e19a584"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_fdb91868b03a2040db408a53331"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c19d0490a6b115b54d749da44e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c63a58631cc618498c506732d"`);
        await queryRunner.query(`DROP TABLE "video_hashtags_hashtag"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4000d356708cf16c3637ff160"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91df686c1a7cf8e715dfbf1e27"`);
        await queryRunner.query(`DROP TABLE "video_mentions_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34d1f902a8a527dbc2502f87c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abbd506a94a424dd6a3a68d26f"`);
        await queryRunner.query(`DROP TABLE "comment_likes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0294c9da809e60b4f2472d4c83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dc73b25397fe92549b4c41dfe5"`);
        await queryRunner.query(`DROP TABLE "comment_mentions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9512bb3043bc3aa26944df0f17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf5b05a1450ae8049082928f85"`);
        await queryRunner.query(`DROP TABLE "bookmark_reels"`);
        await queryRunner.query(`DROP TABLE "otp"`);
        await queryRunner.query(`DROP TABLE "shares"`);
        await queryRunner.query(`DROP TABLE "block"`);
        await queryRunner.query(`DROP TABLE "views"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "chat_sessions"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP TABLE "tokens"`);
        await queryRunner.query(`DROP TABLE "user_profile"`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_star_enum"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TYPE "public"."notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "likes"`);
        await queryRunner.query(`DROP TABLE "video"`);
        await queryRunner.query(`DROP TYPE "public"."video_type_enum"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TABLE "bookmarks"`);
        await queryRunner.query(`DROP TABLE "hashtag"`);
        await queryRunner.query(`DROP TABLE "audio"`);
        await queryRunner.query(`DROP TABLE "follows"`);
    }

}
