version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
#   node:
#     depends_on:
#       - postgres
#     build: .
#     container_name: demo_node
#     working_dir: /app
#     volumes:
#       - .:/app
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env

volumes:
  pg_data: